import Provider from "@/components/helpers/WrapperProvider";
import NavBar from "@/components/ui/NavBar";
import "@uploadthing/react/styles.css";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from "react";
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
    children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
          <Provider>
            <NavBar />
            <div style={{ height: "calc(100vh - var(--navbar-height))" }}>
              {children}
            </div>
          </Provider>
        </div>
      </body>
    </html>
  )
}
